### ISSUE TITLE
Fails while running `bold_wf:bold_get_bold_file_in_bids` and `anat_wf:anat_get_t1w_file_in_bids`

### ISSUE THREAD

**Issue by favour-nerrise** [pBFSLab/DeepPrep#102]
Running the latest version of DeepPrep fails while running `bold_wf:bold_get_bold_file_in_bids` and `anat_wf:anat_get_t1w_file_in_bids`. I have a cluster (Singularity) with 1 core, 24 nodes, and 364 GB of memory. 

```
ERROR ~ Error executing process > 'anat_wf:anat_get_t1w_file_in_bids'

Caused by:
  Process `anat_wf:anat_get_t1w_file_in_bids` terminated with an error exit status (137)

Command executed:

  anat_get_t1w_file_in_bids.py --bids-dir /scratch/groups/redacted/data/redacted2 --subject-ids sub-01

Command exit status:
  137

Command output:
  (empty)

Command error:
  WARNING: SINGULARITYENV_TMPDIR and APPTAINERENV_TMPDIR have different values, using the latter
  INFO:    Environment variable SINGULARITYENV_NXF_TASK_WORKDIR is set, but APPTAINERENV_NXF_TASK_WORKDIR is preferred
  INFO:    Environment variable SINGULARITYENV_NXF_DEBUG is set, but APPTAINERENV_NXF_DEBUG is preferred
  WARNING: Skipping environment variable [SINGULARITYENV_TMPDIR=/tmp], TMPDIR is already overridden with different value [/scratch/groups/redacted/data/derivatives/WorkDir/tmp]
  .command.sh: line 2: 133621 Killed                  anat_get_t1w_file_in_bids.py --bids-dir /scratch/groups/redacted/data/redacted2 --subject-ids sub-01

Work dir:
  /scratch/groups/redacted/data/derivatives/WorkDir/nextflow/0d/422e43a432e91a7e38c4e6078ff467

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

 -- Check '.nextflow.log' file for details
```

Here's my config file:
```
//deepprep.slurm.cpu.config

singularity.enabled = true
singularity.autoMounts = false
singularity.runOptions = '-e \
--home ${output_dir}/WorkDir/home \
--env TEMP=${output_dir}/WorkDir/tmp \
--env TMP=${output_dir}/WorkDir/tmp \
--env TMPDIR=${output_dir}/WorkDir/tmp \
-B ${bids_dir} \
-B ${output_dir} \
-B ${fs_license_file}:/opt/freesurfer/license.txt \
'

process {
//errorStrategy = 'ignore'

    executor = 'slurm'

    queue = 'redacted'

    clusterOptions = { "" }

    container = "${container}"
}
```

Here's my run file:
```
#!/bin/bash

module load python/3.9.0
module load java/18.0.2
module load redis/4.0.1

export TEST_DIR=/scratch/groups/redacted/data
bids_root_dir=/scratch/groups/redacted/data/redacted2

cd ${TEST_DIR}
git clone https://github.com/IndiLab/DeepPrep.git

export FS_LICENSE=$bids_root_dir/derivatives/freesurfer_license.txt
export BIDS_PATH=$bids_root_dir
export OUTPUT_PATH=${TEST_DIR}/derivatives

${TEST_DIR}/DeepPrep/deepprep/deepprep.sh \
${BIDS_PATH} \
${OUTPUT_PATH} \
participant \
--participant_label sub-01 \
--bold_task_type rest \
--bold_volume_space MNI152NLin2009cAsym \
--deepprep_home ${TEST_DIR}/DeepPrep \
--fs_license_file ${FS_LICENSE} \
--executor cluster \
--container ${TEST_DIR}/deepprep_23.1.0.sif \
--config_file ${TEST_DIR}/deepprep.slurm.cpu.config \
--skip_bids_validation \
--device cpu \
--debug \
--resume
```

**Comment by NingAnMe** [comment]
Hi @favour-nerrise, 
It looks like there's an Out-Of-Memory Error with exit stats 137. 
You need to adjust the memory allocation for the process in the **_DeepPrep/deepprep/nextflow/deepprep.nf_** file. 
You can try changing the memory allocation from '100 MB' to '500 MB** on line 19 and line 1404. 
Looking forward to your feedback.

**Comment by favour-nerrise** [comment]
Now it's failing with the error after I cleaned my `/derivatives` output folder:

```
ERROR ~ Error executing process > 'deepprep_init'

Caused by:
  Process `deepprep_init` terminated with an error exit status (135)

Command executed:

  df -h
  
  gpu_schedule_lock.py executor
  
  input_bids_validator.py     --bids_dir /scratch/groups/redacted/data/redacted2     --exec_env docker     --participant_label sub-01     --skip_bids_validation true
  
  deepprep_init.py     --freesurfer_home /opt/freesurfer     --bids_dir /scratch/groups/redacted/data/redacted2     --output_dir /scratch/groups/redacted/data/redacted3     --subjects_dir /scratch/groups/redacted/data/redacted3/Recon     --bold_spaces fsaverage6     --bold_only False

Command exit status:
  135

Command output:
  sherlock.isilon:/ifs/home.users/jdoe         14G  4.3G  9.8G  31% /home/users/jdoe
  sherlock.isilon:/ifs/sherlock/software/modules  1.5P  544T  918T  38% /share/software/modules
  /dev/nvme0n1p2                                   24G  6.1G   18G  26% /etc/hosts
  tmpfs                                           126G     0  126G   0% /sys/fs/cgroup
  set gpu lock
  connect to StrictRedis DB
  Cant connect to StrictRedis DB Error 111 connecting to localhost:6379. Connection refused.
  sending incremental file list
  surf/
  surf/lh.sphere
  surf/lh.sphere.reg
  surf/lh.sphere.reg.avg
  surf/lh.sulc
  surf/lh.thickness
  surf/lh.white
  surf/lh.white.avg.area.mgh
  surf/lh.white_avg
  surf/lh.white_avg.H
  surf/lh.white_avg.K
  surf/mris_preproc.surface.lh.log
  surf/mris_preproc.surface.lh.log.bak
  surf/mris_preproc.surface.rh.log
  surf/mris_preproc.surface.rh.log.bak
  surf/rh.area
  surf/rh.avg_curv
  surf/rh.avg_sulc
  surf/rh.avg_thickness
  surf/rh.curv
  surf/rh.inflated
  surf/rh.inflated_avg
  surf/rh.orig
  surf/rh.orig.avg.area.mgh
  surf/rh.orig_avg
  surf/rh.pial
  surf/rh.pial.avg.area.mgh
  surf/rh.pial_avg
  surf/rh.smoothwm
  surf/rh.sphere
  surf/rh.sphere.reg
  surf/rh.sphere.reg.avg
  surf/rh.sulc
  surf/rh.thickness
  surf/rh.white
  surf/rh.white.avg.area.mgh
  surf/rh.white_avg
  surf/rh.white_avg.H
  surf/rh.white_avg.K
  
  sent 28,134,786 bytes  received 748 bytes  18,757,022.67 bytes/sec
  total size is 116,825,961  speedup is 4.15

Command error:
  WARNING: SINGULARITYENV_TMPDIR and APPTAINERENV_TMPDIR have different values, using the latter
  INFO:    Environment variable SINGULARITYENV_NXF_TASK_WORKDIR is set, but APPTAINERENV_NXF_TASK_WORKDIR is preferred
  INFO:    Environment variable SINGULARITYENV_NXF_DEBUG is set, but APPTAINERENV_NXF_DEBUG is preferred
  WARNING: Skipping environment variable [SINGULARITYENV_TMPDIR=/tmp], TMPDIR is already overridden with different value [/scratch/groups/redacted/data/redacted3/WorkDir/tmp]
  cp: error reading '/opt/freesurfer/subjects/fsaverage/mri/orig.mgz': Transport endpoint is not connected
  .command.run: line 38: 248355 Bus error               ps -e -o pid= -o ppid=
  cp: cannot stat '/opt/freesurfer/subjects/fsaverage/mri/p.aseg.mgz': Transport endpoint is not connected
  cp: cannot stat '/opt/freesurfer/subjects/fsaverage/mri/rh.ribbon.mgz': Transport endpoint is not connected
  cp: cannot stat '/opt/freesurfer/subjects/fsaverage/mri/ribbon.mgz': Transport endpoint is not connected
  cp: cannot stat '/opt/freesurfer/subjects/fsaverage/mri/subcort.mask.1mm.README': Transport endpoint is not connected
  cp: cannot stat '/opt/freesurfer/subjects/fsaverage/mri/subcort.mask.1mm.mgz': Transport endpoint is not connected
  cp: cannot stat '/opt/freesurfer/subjects/fsaverage/mri/subcort.prob.log': Transport endpoint is not connected
  cp: cannot stat '/opt/freesurfer/subjects/fsaverage/mri/subcort.prob.mgz': Transport endpoint is not connected
  cp: cannot stat '/opt/freesurfer/subjects/fsaverage/mri/transforms': Transport endpoint is not connected
  cp: cannot stat '/opt/freesurfer/subjects/fsaverage/mri.2mm': Transport endpoint is not connected
  cp: cannot stat '/opt/freesurfer/subjects/fsaverage/scripts': Transport endpoint is not connected
  cp: cannot stat '/opt/freesurfer/subjects/fsaverage/surf': Transport endpoint is not connected
  cp: cannot stat '/opt/freesurfer/subjects/fsaverage/xhemi': Transport endpoint is not connected
  .command.sh: line 8: 248177 Bus error               deepprep_init.py --freesurfer_home /opt/freesurfer --bids_dir /scratch/groups/redacted/data/redacted2 --output_dir /scratch/groups/redacted/data/redacted3 --subjects_dir /scratch/groups/redacted/data/redacted3/Recon --bold_spaces fsaverage6 --bold_only False
  .command.run: line 165: 247983 Bus error               /bin/bash -ue .command.sh
  /var/spool/slurmd/job43813305/slurm_script: line 294: 247914 Bus error               env - PATH="$PATH" ${TMP:+SINGULARITYENV_TMP="$TMP"} ${TMPDIR:+SINGULARITYENV_TMPDIR="$TMPDIR"} ${NXF_TASK_WORKDIR:+SINGULARITYENV_NXF_TASK_WORKDIR="$NXF_TASK_WORKDIR"} SINGULARITYENV_NXF_DEBUG="${NXF_DEBUG:=0}" singularity exec --no-home --pid -e --home /scratch/groups/redacted/data/redacted3/WorkDir/home --env TEMP=/scratch/groups/redacted/data/redacted3/WorkDir/tmp --env TMP=/scratch/groups/redacted/data/redacted3/WorkDir/tmp --env TMPDIR=/scratch/groups/redacted/data/redacted3/WorkDir/tmp -B /scratch/groups/redacted/data/redacted2 -B /scratch/groups/redacted/data/redacted3 -B /scratch/groups/redacted/data/redacted2/derivatives/freesurfer_license.txt:/opt/freesurfer/license.txt /scratch/groups/redacted/data/deepprep_23.1.0.sif /bin/bash -c "cd $PWD; eval $(nxf_container_env); /bin/bash .command.run nxf_trace"

Work dir:
  /scratch/groups/redacted/data/redacted3/WorkDir/nextflow/90/f02fd7698e0abdb2ddec20a06acf62

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

 -- Check '.nextflow.log' file for details
```

**Comment by favour-nerrise** [comment]
Update: it now randomly worked passed the `gpu_schedule_lock` error in `deepprep_init`. 

However, it's failing for my subject with multiple runs per session: 
```
ERROR ~ Error executing process > 'anat_wf:anat_motioncor (sub-01)'

Caused by:
  Process `anat_wf:anat_motioncor (sub-01)` terminated with an error exit status (1)

Command executed:

  recon-all -sd /scratch/groups/redacted/data/derivatives/Recon -subject sub-01 -motioncor -threads 1 -itkthreads 1 -no-isrunning

Command exit status:
  1

Command output:
  --lta: Will output LTA transforms
  Setting iscale ...
  reading source '/scratch/groups/redacted/data/derivatives/Recon/sub-01/mri/orig/001.mgz'...
  converting source '/scratch/groups/redacted/data/derivatives/Recon/sub-01/mri/orig/001.mgz' to bspline ...
  MRItoBSpline degree 3
  reading source '/scratch/groups/redacted/data/derivatives/Recon/sub-01/mri/orig/002.mgz'...
  converting source '/scratch/groups/redacted/data/derivatives/Recon/sub-01/mri/orig/002.mgz' to bspline ...
  MRItoBSpline degree 3
  reading source '/scratch/groups/redacted/data/derivatives/Recon/sub-01/mri/orig/003.mgz'...
  converting source '/scratch/groups/redacted/data/derivatives/Recon/sub-01/mri/orig/003.mgz' to bspline ...
  MRItoBSpline degree 3
  reading source '/scratch/groups/redacted/data/derivatives/Recon/sub-01/mri/orig/004.mgz'...
  converting source '/scratch/groups/kpohl/data/derivatives/Recon/sub-01/mri/orig/004.mgz' to bspline ...
  MRItoBSpline degree 3
  reading source '/scratch/groups/redacted/data/derivatives/Recon/sub-01/mri/orig/005.mgz'...
  converting source '/scratch/groups/redacted/data/derivatives/Recon/sub-01/mri/orig/005.mgz' to bspline ...
  MRItoBSpline degree 3
  
  MultiRegistration::initializing Xforms (init 1 , maxres 0 , iterate 5 , epsit 0.01 ) : 
  
  [init] ========================= TP 2 to TP 1 ==============================
           Register TP 2 ( /scratch/groups/kpohl/data/ppmi_fmri_derivatives/Recon/sub-01/mri/orig/002.mgz )
            to      TP 1 ( /scratch/groups/kpohl/data/ppmi_fmri_derivatives/Recon/sub-01/mri/orig/001.mgz )
  
         -- Original : (0.5, 0.5, 1.5)mm and (448, 448, 16) voxels.
         -- Resampled: (0.5, 0.5, 0.5)mm and (448, 448, 48) voxels.
         -- Reslicing using cubic bspline 
  MRItoBSpline degree 3
         -- Original : (0.5, 0.5, 1.5)mm and (448, 448, 16) voxels.
         -- Resampled: (0.5, 0.5, 0.5)mm and (448, 448, 48) voxels.
         -- Reslicing using cubic bspline 
  MRItoBSpline degree 3
  
   ========================================================================
   WARNING: image might be too small (or ill shaped) for --satit to work.
            Try to manually specify --sat # if not satisfied with result! 
   ========================================================================
  
  
     - Max Resolution used: 1
       -- gpS ( 224 , 224 , 24 )
       -- gpT ( 224 , 224 , 24 )
  Killed
  Linux sh03-13n05.int 3.10.0-1160.108.1.el7.x86_64 #1 SMP Thu Jan 25 16:17:31 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
  
  recon-all -s sub-01 exited with ERRORS at Wed Mar 27 11:22:17 PDT 2024
  
  For more details, see the log file /scratch/groups/redacted/data/derivatives/Recon/sub-01/scripts/recon-all.log
  To report a problem, see http://surfer.nmr.mgh.harvard.edu/fswiki/BugReporting

Command error:
  WARNING: SINGULARITYENV_TMPDIR and APPTAINERENV_TMPDIR have different values, using the latter
  INFO:    Environment variable SINGULARITYENV_NXF_TASK_WORKDIR is set, but APPTAINERENV_NXF_TASK_WORKDIR is preferred
  INFO:    Environment variable SINGULARITYENV_NXF_DEBUG is set, but APPTAINERENV_NXF_DEBUG is preferred
  WARNING: Skipping environment variable [SINGULARITYENV_TMPDIR=/tmp], TMPDIR is already overridden with different value [/scratch/groups/redacted/data/derivatives/WorkDir/tmp]

Work dir:
  /scratch/groups/redacted/data/derivatives/WorkDir/nextflow/6d/1273f911382c76b6fc13cebeba8803

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line

 -- Check '.nextflow.log' file for details
```

Is there something else I have to modify for running `MultiRegistration`?

**Comment by NingAnMe** [comment]
> @NingAnMe Now it's failing with the error after I cleaned my `/derivatives` output folder:
> 
> ```
> ERROR ~ Error executing process > 'deepprep_init'
> 
> Caused by:
>   Process `deepprep_init` terminated with an error exit status (135)
> 
> Command executed:
> 
>   df -h
>   
>   gpu_schedule_lock.py executor
>   
>   input_bids_validator.py     --bids_dir /scratch/groups/redacted/data/redacted2     --exec_env docker     --participant_label sub-01     --skip_bids_validation true
>   
>   deepprep_init.py     --freesurfer_home /opt/freesurfer     --bids_dir /scratch/groups/redacted/data/redacted2     --output_dir /scratch/groups/redacted/data/redacted3     --subjects_dir /scratch/groups/redacted/data/redacted3/Recon     --bold_spaces fsaverage6     --bold_only False
> 
> Command exit status:
>   135
> 
> Command output:
>   sherlock.isilon:/ifs/home.users/jdoe         14G  4.3G  9.8G  31% /home/users/jdoe
>   sherlock.isilon:/ifs/sherlock/software/modules  1.5P  544T  918T  38% /share/software/modules
>   /dev/nvme0n1p2                                   24G  6.1G   18G  26% /etc/hosts
>   tmpfs                                           126G     0  126G   0% /sys/fs/cgroup
>   set gpu lock
>   connect to StrictRedis DB
>   Cant connect to StrictRedis DB Error 111 connecting to localhost:6379. Connection refused.
>   sending incremental file list
>   surf/
>   surf/lh.sphere
>   surf/lh.sphere.reg
>   surf/lh.sphere.reg.avg
>   surf/lh.sulc
>   surf/lh.thickness
>   surf/lh.white
>   surf/lh.white.avg.area.mgh
>   surf/lh.white_avg
>   surf/lh.white_avg.H
>   surf/lh.white_avg.K
>   surf/mris_preproc.surface.lh.log
>   surf/mris_preproc.surface.lh.log.bak
>   surf/mris_preproc.surface.rh.log
>   surf/mris_preproc.surface.rh.log.bak
>   surf/rh.area
>   surf/rh.avg_curv
>   surf/rh.avg_sulc
>   surf/rh.avg_thickness
>   surf/rh.curv
>   surf/rh.inflated
>   surf/rh.inflated_avg
>   surf/rh.orig
>   surf/rh.orig.avg.area.mgh
>   surf/rh.orig_avg
>   surf/rh.pial
>   surf/rh.pial.avg.area.mgh
>   surf/rh.pial_avg
>   surf/rh.smoothwm
>   surf/rh.sphere
>   surf/rh.sphere.reg
>   surf/rh.sphere.reg.avg
>   surf/rh.sulc
>   surf/rh.thickness
>   surf/rh.white
>   surf/rh.white.avg.area.mgh
>   surf/rh.white_avg
>   surf/rh.white_avg.H
>   surf/rh.white_avg.K
>   
>   sent 28,134,786 bytes  received 748 bytes  18,757,022.67 bytes/sec
>   total size is 116,825,961  speedup is 4.15
> 
> Command error:
>   WARNING: SINGULARITYENV_TMPDIR and APPTAINERENV_TMPDIR have different values, using the latter
>   INFO:    Environment variable SINGULARITYENV_NXF_TASK_WORKDIR is set, but APPTAINERENV_NXF_TASK_WORKDIR is preferred
>   INFO:    Environment variable SINGULARITYENV_NXF_DEBUG is set, but APPTAINERENV_NXF_DEBUG is preferred
>   WARNING: Skipping environment variable [SINGULARITYENV_TMPDIR=/tmp], TMPDIR is already overridden with different value [/scratch/groups/redacted/data/redacted3/WorkDir/tmp]
>   cp: error reading '/opt/freesurfer/subjects/fsaverage/mri/orig.mgz': Transport endpoint is not connected
>   .command.run: line 38: 248355 Bus error               ps -e -o pid= -o ppid=
>   cp: cannot stat '/opt/freesurfer/subjects/fsaverage/mri/p.aseg.mgz': Transport endpoint is not connected
>   cp: cannot stat '/opt/freesurfer/subjects/fsaverage/mri/rh.ribbon.mgz': Transport endpoint is not connected
>   cp: cannot stat '/opt/freesurfer/subjects/fsaverage/mri/ribbon.mgz': Transport endpoint is not connected
>   cp: cannot stat '/opt/freesurfer/subjects/fsaverage/mri/subcort.mask.1mm.README': Transport endpoint is not connected
>   cp: cannot stat '/opt/freesurfer/subjects/fsaverage/mri/subcort.mask.1mm.mgz': Transport endpoint is not connected
>   cp: cannot stat '/opt/freesurfer/subjects/fsaverage/mri/subcort.prob.log': Transport endpoint is not connected
>   cp: cannot stat '/opt/freesurfer/subjects/fsaverage/mri/subcort.prob.mgz': Transport endpoint is not connected
>   cp: cannot stat '/opt/freesurfer/subjects/fsaverage/mri/transforms': Transport endpoint is not connected
>   cp: cannot stat '/opt/freesurfer/subjects/fsaverage/mri.2mm': Transport endpoint is not connected
>   cp: cannot stat '/opt/freesurfer/subjects/fsaverage/scripts': Transport endpoint is not connected
>   cp: cannot stat '/opt/freesurfer/subjects/fsaverage/surf': Transport endpoint is not connected
>   cp: cannot stat '/opt/freesurfer/subjects/fsaverage/xhemi': Transport endpoint is not connected
>   .command.sh: line 8: 248177 Bus error               deepprep_init.py --freesurfer_home /opt/freesurfer --bids_dir /scratch/groups/redacted/data/redacted2 --output_dir /scratch/groups/redacted/data/redacted3 --subjects_dir /scratch/groups/redacted/data/redacted3/Recon --bold_spaces fsaverage6 --bold_only False
>   .command.run: line 165: 247983 Bus error               /bin/bash -ue .command.sh
>   /var/spool/slurmd/job43813305/slurm_script: line 294: 247914 Bus error               env - PATH="$PATH" ${TMP:+SINGULARITYENV_TMP="$TMP"} ${TMPDIR:+SINGULARITYENV_TMPDIR="$TMPDIR"} ${NXF_TASK_WORKDIR:+SINGULARITYENV_NXF_TASK_WORKDIR="$NXF_TASK_WORKDIR"} SINGULARITYENV_NXF_DEBUG="${NXF_DEBUG:=0}" singularity exec --no-home --pid -e --home /scratch/groups/redacted/data/redacted3/WorkDir/home --env TEMP=/scratch/groups/redacted/data/redacted3/WorkDir/tmp --env TMP=/scratch/groups/redacted/data/redacted3/WorkDir/tmp --env TMPDIR=/scratch/groups/redacted/data/redacted3/WorkDir/tmp -B /scratch/groups/redacted/data/redacted2 -B /scratch/groups/redacted/data/redacted3 -B /scratch/groups/redacted/data/redacted2/derivatives/freesurfer_license.txt:/opt/freesurfer/license.txt /scratch/groups/redacted/data/deepprep_23.1.0.sif /bin/bash -c "cd $PWD; eval $(nxf_container_env); /bin/bash .command.run nxf_trace"
> 
> Work dir:
>   /scratch/groups/redacted/data/redacted3/WorkDir/nextflow/90/f02fd7698e0abdb2ddec20a06acf62
> 
> Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`
> 
>  -- Check '.nextflow.log' file for details
> ```

Hi, @favour-nerrise ,
I think this is a connectivity problem between two store nodes. I've added a retry feature to the "deepprep_init" process. If Nextflow runs into this issue, it will retry three times.

```
    errorStrategy { task.exitStatus == 135 ? 'retry' : 'terminate' }
    maxRetries 3
```

**Comment by NingAnMe** [comment]
> Update: it now randomly worked passed the `gpu_schedule_lock` error in `deepprep_init`.
> 
> However, it's failing for my subject with multiple runs per session:
> 
> ```
> ERROR ~ Error executing process > 'anat_wf:anat_motioncor (sub-01)'
> 
> Caused by:
>   Process `anat_wf:anat_motioncor (sub-01)` terminated with an error exit status (1)
> 
> Command executed:
> 
>   recon-all -sd /scratch/groups/redacted/data/derivatives/Recon -subject sub-01 -motioncor -threads 1 -itkthreads 1 -no-isrunning
> 
> Command exit status:
>   1
> 
> Command output:
>   --lta: Will output LTA transforms
>   Setting iscale ...
>   reading source '/scratch/groups/redacted/data/derivatives/Recon/sub-01/mri/orig/001.mgz'...
>   converting source '/scratch/groups/redacted/data/derivatives/Recon/sub-01/mri/orig/001.mgz' to bspline ...
>   MRItoBSpline degree 3
>   reading source '/scratch/groups/redacted/data/derivatives/Recon/sub-01/mri/orig/002.mgz'...
>   converting source '/scratch/groups/redacted/data/derivatives/Recon/sub-01/mri/orig/002.mgz' to bspline ...
>   MRItoBSpline degree 3
>   reading source '/scratch/groups/redacted/data/derivatives/Recon/sub-01/mri/orig/003.mgz'...
>   converting source '/scratch/groups/redacted/data/derivatives/Recon/sub-01/mri/orig/003.mgz' to bspline ...
>   MRItoBSpline degree 3
>   reading source '/scratch/groups/redacted/data/derivatives/Recon/sub-01/mri/orig/004.mgz'...
>   converting source '/scratch/groups/kpohl/data/derivatives/Recon/sub-01/mri/orig/004.mgz' to bspline ...
>   MRItoBSpline degree 3
>   reading source '/scratch/groups/redacted/data/derivatives/Recon/sub-01/mri/orig/005.mgz'...
>   converting source '/scratch/groups/redacted/data/derivatives/Recon/sub-01/mri/orig/005.mgz' to bspline ...
>   MRItoBSpline degree 3
>   
>   MultiRegistration::initializing Xforms (init 1 , maxres 0 , iterate 5 , epsit 0.01 ) : 
>   
>   [init] ========================= TP 2 to TP 1 ==============================
>            Register TP 2 ( /scratch/groups/kpohl/data/ppmi_fmri_derivatives/Recon/sub-01/mri/orig/002.mgz )
>             to      TP 1 ( /scratch/groups/kpohl/data/ppmi_fmri_derivatives/Recon/sub-01/mri/orig/001.mgz )
>   
>          -- Original : (0.5, 0.5, 1.5)mm and (448, 448, 16) voxels.
>          -- Resampled: (0.5, 0.5, 0.5)mm and (448, 448, 48) voxels.
>          -- Reslicing using cubic bspline 
>   MRItoBSpline degree 3
>          -- Original : (0.5, 0.5, 1.5)mm and (448, 448, 16) voxels.
>          -- Resampled: (0.5, 0.5, 0.5)mm and (448, 448, 48) voxels.
>          -- Reslicing using cubic bspline 
>   MRItoBSpline degree 3
>   
>    ========================================================================
>    WARNING: image might be too small (or ill shaped) for --satit to work.
>             Try to manually specify --sat # if not satisfied with result! 
>    ========================================================================
>   
>   
>      - Max Resolution used: 1
>        -- gpS ( 224 , 224 , 24 )
>        -- gpT ( 224 , 224 , 24 )
>   Killed
>   Linux sh03-13n05.int 3.10.0-1160.108.1.el7.x86_64 #1 SMP Thu Jan 25 16:17:31 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
>   
>   recon-all -s sub-01 exited with ERRORS at Wed Mar 27 11:22:17 PDT 2024
>   
>   For more details, see the log file /scratch/groups/redacted/data/derivatives/Recon/sub-01/scripts/recon-all.log
>   To report a problem, see http://surfer.nmr.mgh.harvard.edu/fswiki/BugReporting
> 
> Command error:
>   WARNING: SINGULARITYENV_TMPDIR and APPTAINERENV_TMPDIR have different values, using the latter
>   INFO:    Environment variable SINGULARITYENV_NXF_TASK_WORKDIR is set, but APPTAINERENV_NXF_TASK_WORKDIR is preferred
>   INFO:    Environment variable SINGULARITYENV_NXF_DEBUG is set, but APPTAINERENV_NXF_DEBUG is preferred
>   WARNING: Skipping environment variable [SINGULARITYENV_TMPDIR=/tmp], TMPDIR is already overridden with different value [/scratch/groups/redacted/data/derivatives/WorkDir/tmp]
> 
> Work dir:
>   /scratch/groups/redacted/data/derivatives/WorkDir/nextflow/6d/1273f911382c76b6fc13cebeba8803
> 
> Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line
> 
>  -- Check '.nextflow.log' file for details
> ```
> 
> Is there something else I have to modify for running `MultiRegistration`?

I think this is a memory problem like "anat_get_t1w_file_in_bids". I've added a retry feature to this 
 process. If Nextflow runs into this issue, it will retry twice.

I processed a dataset for one subject with ten T1w files and discovered that it will require 2 GB of memory. We had previously set it to '1 GB'.

```
    memory { 1.GB * task.attempt }

    errorStrategy { task.exitStatus == 1 ? 'retry' : 'terminate' }
    maxRetries 2
```

**Comment by NingAnMe** [comment]
Hi, @favour-nerrise,
Sorry for the long wait. 
I've addressed these issues by merging #108. You can pull the code and give it another try. 
Thanks for trying out DeepPrep.

**Comment by NingAnMe** [comment]
> Thank you for the fixes! @NingAnMe
> 
> Unfortunately, I'm running into a new issue on `anat_segment` with connecting to the Redis database. When I ran with `cpu.config` I thought it was due to not have gpu since it showed an error output of failing on `gpu_schedule_run`. I re-ran with `gpu.config` instead and am still getting a similar error:
> 
> ```
> ERROR ~ Error executing process > 'anat_wf:anat_segment (sub-01)'
> 
> Caused by:
>   Process `anat_wf:anat_segment (sub-01)` terminated with an error exit status (1)
> 
> Command executed:
> 
>   gpu_schedule_run.py gpu double executor /opt/DeepPrep/deepprep/FastSurfer/FastSurferCNN/eval.py     --in_name /scratch/groups/redacted/data/ppmi_fmri_derivatives/Recon/sub-01/mri/orig.mgz     --out_name /scratch/groups/redacted/data/ppmi_fmri_derivatives/Recon/sub-01/mri/aparc.DKTatlas+aseg.deep.mgz     --conformed_name /scratch/groups/redacted/data/ppmi_fmri_derivatives/Recon/sub-01/mri/conformed.mgz     --order 1     --network_sagittal_path /opt/DeepPrep/deepprep/FastSurfer/checkpoints/Sagittal_Weights_FastSurferCNN/ckpts/Epoch_30_training_state.pkl     --network_coronal_path /opt/DeepPrep/deepprep/FastSurfer/checkpoints/Coronal_Weights_FastSurferCNN/ckpts/Epoch_30_training_state.pkl     --network_axial_path /opt/DeepPrep/deepprep/FastSurfer/checkpoints/Axial_Weights_FastSurferCNN/ckpts/Epoch_30_training_state.pkl     --batch_size 1 --simple_run --run_viewagg_on check
> 
> Command exit status:
>   1
> 
> Command output:
>   Auto select GPU by ： gpu
>   GPU INFO: 
>   ['0, Tesla P40, 22905 MiB, 23040 MiB, 9.59 W, 250.00 W\n']
>   GPU INFO: 
>   ['0, Tesla P40, 22905 MiB, 23040 MiB, 9.59 W, 250.00 W\n']
>   Choosing the GPU device has largest free memory...
>   Sorted by free memory size
>   Using GPU 0:
>   index:0
>   gpu_name:Tesla P40
>   memory.free:22905
>   memory.total:23040
>   power.draw:9
>   power.limit:250
>   specified:False
>   INFO: GPU: 0
>   INFO: sys.argv : ['/opt/DeepPrep/deepprep/nextflow/bin/gpu_schedule_run.py', 'gpu', 'double', 'executor', '/opt/DeepPrep/deepprep/FastSurfer/FastSurferCNN/eval.py', '--in_name', '/scratch/groups/redacted/data/ppmi_fmri_derivatives/Recon/sub-01/mri/orig.mgz', '--out_name', '/scratch/groups/redacted/data/ppmi_fmri_derivatives/Recon/sub-01/mri/aparc.DKTatlas+aseg.deep.mgz', '--conformed_name', '/scratch/groups/redacted/data/ppmi_fmri_derivatives/Recon/sub-01/mri/conformed.mgz', '--order', '1', '--network_sagittal_path', '/opt/DeepPrep/deepprep/FastSurfer/checkpoints/Sagittal_Weights_FastSurferCNN/ckpts/Epoch_30_training_state.pkl', '--network_coronal_path', '/opt/DeepPrep/deepprep/FastSurfer/checkpoints/Coronal_Weights_FastSurferCNN/ckpts/Epoch_30_training_state.pkl', '--network_axial_path', '/opt/DeepPrep/deepprep/FastSurfer/checkpoints/Axial_Weights_FastSurferCNN/ckpts/Epoch_30_training_state.pkl', '--batch_size', '1', '--simple_run', '--run_viewagg_on', 'check']
>   connect to StrictRedis DB
>   INFO: run_count : two
> 
> Command error:
>   INFO:    Environment variable SINGULARITYENV_TMPDIR is set, but APPTAINERENV_TMPDIR is preferred
>   INFO:    Environment variable SINGULARITYENV_NXF_TASK_WORKDIR is set, but APPTAINERENV_NXF_TASK_WORKDIR is preferred
>   INFO:    Environment variable SINGULARITYENV_NXF_DEBUG is set, but APPTAINERENV_NXF_DEBUG is preferred
>   INFO:    underlay of /usr/bin/nvidia-smi required more than 50 (455) bind mounts
>   Traceback (most recent call last):
>     File "/usr/local/lib/python3.10/dist-packages/redis/connection.py", line 276, in connect
>       sock = self.retry.call_with_retry(
>     File "/usr/local/lib/python3.10/dist-packages/redis/retry.py", line 46, in call_with_retry
>       return do()
>     File "/usr/local/lib/python3.10/dist-packages/redis/connection.py", line 277, in <lambda>
>       lambda: self._connect(), lambda error: self.disconnect(error)
>     File "/usr/local/lib/python3.10/dist-packages/redis/connection.py", line 639, in _connect
>       raise err
>     File "/usr/local/lib/python3.10/dist-packages/redis/connection.py", line 627, in _connect
>       sock.connect(socket_address)
>   ConnectionRefusedError: [Errno 111] Connection refused
>   
>   During handling of the above exception, another exception occurred:
>   
>   Traceback (most recent call last):
>     File "/opt/DeepPrep/deepprep/nextflow/bin/gpu_schedule_run.py", line 49, in <module>
>       lock_i = int(conn.lpop('lock_index'))
>     File "/usr/local/lib/python3.10/dist-packages/redis/commands/core.py", line 2727, in lpop
>       return self.execute_command("LPOP", name)
>     File "/usr/local/lib/python3.10/dist-packages/redis/client.py", line 540, in execute_command
>       conn = self.connection or pool.get_connection(command_name, **options)
> ```
> 
> ```
> ERROR ~ Error executing process > 'anat_wf:anat_segment (sub-01)'
> 
> Caused by:
>   Process `anat_wf:anat_segment (sub-01)` terminated with an error exit status (1)
> 
> Command executed:
> 
>   gpu_schedule_run.py gpu double executor /opt/DeepPrep/deepprep/FastSurfer/FastSurferCNN/eval.py     --in_name /scratch/groups/redacted/data/ppmi_fmri_derivatives/Recon/sub-01/mri/orig.mgz     --out_name /scratch/groups/redacted/data/ppmi_fmri_derivatives/Recon/sub-01/mri/aparc.DKTatlas+aseg.deep.mgz     --conformed_name /scratch/groups/redacted/data/ppmi_fmri_derivatives/Recon/sub-01/mri/conformed.mgz     --order 1     --network_sagittal_path /opt/DeepPrep/deepprep/FastSurfer/checkpoints/Sagittal_Weights_FastSurferCNN/ckpts/Epoch_30_training_state.pkl     --network_coronal_path /opt/DeepPrep/deepprep/FastSurfer/checkpoints/Coronal_Weights_FastSurferCNN/ckpts/Epoch_30_training_state.pkl     --network_axial_path /opt/DeepPrep/deepprep/FastSurfer/checkpoints/Axial_Weights_FastSurferCNN/ckpts/Epoch_30_training_state.pkl     --batch_size 1 --simple_run --run_viewagg_on check
> 
> Command exit status:
>   1
> 
> Command output:
>   Auto select GPU by ： gpu
>   GPU INFO: 
>   ['0, Tesla P40, 22905 MiB, 23040 MiB, 9.59 W, 250.00 W\n']
>   GPU INFO: 
>   ['0, Tesla P40, 22905 MiB, 23040 MiB, 9.59 W, 250.00 W\n']
>   Choosing the GPU device has largest free memory...
>   Sorted by free memory size
>   Using GPU 0:
>   index:0
>   gpu_name:Tesla P40
>   memory.free:22905
>   memory.total:23040
>   power.draw:9
>   power.limit:250
>   specified:False
>   INFO: GPU: 0
>   INFO: sys.argv : ['/opt/DeepPrep/deepprep/nextflow/bin/gpu_schedule_run.py', 'gpu', 'double', 'executor', '/opt/DeepPrep/deepprep/FastSurfer/FastSurferCNN/eval.py', '--in_name', '/scratch/groups/redacted/data/ppmi_fmri_derivatives/Recon/sub-01/mri/orig.mgz', '--out_name', '/scratch/groups/redacted/data/ppmi_fmri_derivatives/Recon/sub-01/mri/aparc.DKTatlas+aseg.deep.mgz', '--conformed_name', '/scratch/groups/redacted/data/ppmi_fmri_derivatives/Recon/sub-01/mri/conformed.mgz', '--order', '1', '--network_sagittal_path', '/opt/DeepPrep/deepprep/FastSurfer/checkpoints/Sagittal_Weights_FastSurferCNN/ckpts/Epoch_30_training_state.pkl', '--network_coronal_path', '/opt/DeepPrep/deepprep/FastSurfer/checkpoints/Coronal_Weights_FastSurferCNN/ckpts/Epoch_30_training_state.pkl', '--network_axial_path', '/opt/DeepPrep/deepprep/FastSurfer/checkpoints/Axial_Weights_FastSurferCNN/ckpts/Epoch_30_training_state.pkl', '--batch_size', '1', '--simple_run', '--run_viewagg_on', 'check']
>   connect to StrictRedis DB
>   INFO: run_count : two
> 
> Command error:
>   INFO:    Environment variable SINGULARITYENV_TMPDIR is set, but APPTAINERENV_TMPDIR is preferred
>   INFO:    Environment variable SINGULARITYENV_NXF_TASK_WORKDIR is set, but APPTAINERENV_NXF_TASK_WORKDIR is preferred
>   INFO:    Environment variable SINGULARITYENV_NXF_DEBUG is set, but APPTAINERENV_NXF_DEBUG is preferred
>   INFO:    underlay of /usr/bin/nvidia-smi required more than 50 (455) bind mounts
>   Traceback (most recent call last):
>     File "/usr/local/lib/python3.10/dist-packages/redis/connection.py", line 276, in connect
>       sock = self.retry.call_with_retry(
>     File "/usr/local/lib/python3.10/dist-packages/redis/retry.py", line 46, in call_with_retry
>       return do()
>     File "/usr/local/lib/python3.10/dist-packages/redis/connection.py", line 277, in <lambda>
>       lambda: self._connect(), lambda error: self.disconnect(error)
>     File "/usr/local/lib/python3.10/dist-packages/redis/connection.py", line 639, in _connect
>       raise err
>     File "/usr/local/lib/python3.10/dist-packages/redis/connection.py", line 627, in _connect
>       sock.connect(socket_address)
>   ConnectionRefusedError: [Errno 111] Connection refused
>   
>   During handling of the above exception, another exception occurred:
>   
>   Traceback (most recent call last):
>     File "/opt/DeepPrep/deepprep/nextflow/bin/gpu_schedule_run.py", line 49, in <module>
>       lock_i = int(conn.lpop('lock_index'))
>     File "/usr/local/lib/python3.10/dist-packages/redis/commands/core.py", line 2727, in lpop
>       return self.execute_command("LPOP", name)
>     File "/usr/local/lib/python3.10/dist-packages/redis/client.py", line 540, in execute_command
>       conn = self.connection or pool.get_connection(command_name, **options)
>     File "/usr/local/lib/python3.10/dist-packages/redis/connection.py", line 1104, in get_connection
>       connection.connect()
>     File "/usr/local/lib/python3.10/dist-packages/redis/connection.py", line 282, in connect
>       raise ConnectionError(self._error_message(e))
>   redis.exceptions.ConnectionError: Error 111 connecting to localhost:6379. Connection refused.
> 
> Work dir:
>   /scratch/groups/redacted/data/ppmi_fmri_derivatives/WorkDir/nextflow/f2/39010ae3b30097cb5caf21b900720e
> 
> Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`
> 
>  -- Check '.nextflow.log' file for details
> ```

I'm sorry for making you wait so long. @favour-nerrise .
I have fixed the bug related to the Redis server. You can download the updated Sif image from Google Drive to run it again.  https://drive.google.com/drive/folders/13txuhCNW_nHG4NX3cl7HehlBJ1ZVB5CV?usp=drive_link
But I can't promise that DeepPrep will work properly with a P40 GPU. Looking forward to your feedback.

**Comment by favour-nerrise** [comment]
Thank you! I switched GPUs and pulled the latest image. Made some progress and then got stuck here. I tried increasing `maxRetries` to 3 but it still failed. 

```
ERROR ~ Error executing process > 'bold_wf:bold_synthmorph_affine (sub-03)'

Caused by:
  Process `bold_wf:bold_synthmorph_affine (sub-03)` terminated with an error exit status (1)

Command executed:

  gpu_schedule_run.py gpu double executor /opt/DeepPrep/deepprep/SynthMorph/bold_synthmorph_affine.py     --bold_preprocess_dir /scratch/groups/redacted/data/ppmi_fmri_derivatives/BOLD     --subject_id sub-03     --synth_script /opt/DeepPrep/deepprep/SynthMorph/mri_bold_synthmorph.py     --t1_native2mm /scratch/groups/redacted/data/ppmi_fmri_derivatives/BOLD/sub-03/anat/sub-03_space-T1w_res-2mm_desc-skull_T1w.nii.gz     --template_space MNI152NLin2009cAsym     --synth_model_path /opt/DeepPrep/deepprep/model/SynthMorph/models

Command exit status:
  1

Command output:
  INFO: Device: gpu
  Auto select GPU by ： gpu
  GPU INFO: 
  ['0, NVIDIA GeForce RTX 2080 Ti, 11010 MiB, 11264 MiB, 23.85 W, 224.00 W\n']
  GPU INFO: 
  ['0, NVIDIA GeForce RTX 2080 Ti, 11010 MiB, 11264 MiB, 23.85 W, 224.00 W\n']
  Choosing the GPU device has largest free memory...
  Sorted by free memory size
  Using GPU 0:
  index:0
  gpu_name:NVIDIA GeForce RTX 2080 Ti
  memory.free:11010
  memory.total:11264
  power.draw:23
  power.limit:224
  specified:False
  INFO: GPU: 0
  INFO: sys.argv : ['/opt/DeepPrep/deepprep/nextflow/bin/gpu_schedule_run.py', 'gpu', 'double', 'executor', '/opt/DeepPrep/deepprep/SynthMorph/bold_synthmorph_affine.py', '--bold_preprocess_dir', '/scratch/groups/redacted/data/ppmi_fmri_derivatives/BOLD', '--subject_id', 'sub-03', '--synth_script', '/opt/DeepPrep/deepprep/SynthMorph/mri_bold_synthmorph.py', '--t1_native2mm', '/scratch/groups/redacted/data/ppmi_fmri_derivatives/BOLD/sub-03/anat/sub-03_space-T1w_res-2mm_desc-skull_T1w.nii.gz', '--template_space', 'MNI152NLin2009cAsym', '--synth_model_path', '/opt/DeepPrep/deepprep/model/SynthMorph/models']
  Cant connect to StrictRedis DB: Error 111 connecting to localhost:6379. Connection refused.
  INFO: GPU: python3 /opt/DeepPrep/deepprep/SynthMorph/bold_synthmorph_affine.py --bold_preprocess_dir /scratch/groups/redacted/data/ppmi_fmri_derivatives/BOLD --subject_id sub-03 --synth_script /opt/DeepPrep/deepprep/SynthMorph/mri_bold_synthmorph.py --t1_native2mm /scratch/groups/redacted/data/ppmi_fmri_derivatives/BOLD/sub-03/anat/sub-03_space-T1w_res-2mm_desc-skull_T1w.nii.gz --template_space MNI152NLin2009cAsym --synth_model_path /opt/DeepPrep/deepprep/model/SynthMorph/models
  Downloading https://templateflow.s3.amazonaws.com/tpl-MNI152NLin2009cAsym/tpl-MNI152NLin2009cAsym_res-02_T1w.nii.gz
  Traceback (most recent call last):
    File "/opt/DeepPrep/deepprep/SynthMorph/bold_synthmorph_affine.py", line 40, in <module>
      template = tflow.get(args.template_space, desc=None, resolution=2, suffix='T1w', extension='nii.gz')
    File "/usr/local/lib/python3.10/dist-packages/templateflow/conf/__init__.py", line 69, in wrapper
      return func(*args, **kwargs)
    File "/usr/local/lib/python3.10/dist-packages/templateflow/api.py", line 145, in get
      _s3_get(filepath)
    File "/usr/local/lib/python3.10/dist-packages/templateflow/api.py", line 308, in _s3_get
      with filepath.open("wb") as f:
    File "/usr/lib/python3.10/pathlib.py", line 1119, in open
      return self._accessor.open(self, mode, buffering, encoding, errors,
  OSError: [Errno 30] Read-only file system: '/opt/TemplateFlow/tpl-MNI152NLin2009cAsym/tpl-MNI152NLin2009cAsym_res-02_T1w.nii.gz'

Command error:
  INFO:    Environment variable SINGULARITYENV_TMPDIR is set, but APPTAINERENV_TMPDIR is preferred
  INFO:    Environment variable SINGULARITYENV_NXF_DEBUG is set, but APPTAINERENV_NXF_DEBUG is preferred
  INFO:    underlay of /usr/bin/nvidia-smi required more than 50 (455) bind mounts
  Traceback (most recent call last):
    File "/opt/DeepPrep/deepprep/nextflow/bin/gpu_schedule_run.py", line 76, in <module>
      assert status == 0
  AssertionError

Work dir:
  /scratch/groups/redacted/data/ppmi_fmri_derivatives/WorkDir/nextflow/b3/16d50da9e528299e6c44eb4872b51a

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`

 -- Check '.nextflow.log' file for details
```

**Comment by NingAnMe** [comment]
@favour-nerrise Sorry for the problem. It looks like there is a directory permission error. You can add a '--templateflow_home ${TEST_DIR}/TemplateFlow' flag to modify the default directory. 

```
${TEST_DIR}/DeepPrep/deepprep/deepprep.sh \
${BIDS_PATH} \
${OUTPUT_PATH} \
participant \
--participant_label sub-01 \
--bold_task_type rest \
--bold_volume_space MNI152NLin2009cAsym \
--deepprep_home ${TEST_DIR}/DeepPrep \
--fs_license_file ${FS_LICENSE} \
--executor cluster \
--container ${TEST_DIR}/deepprep_23.1.0.sif \
--config_file ${TEST_DIR}/deepprep.slurm.cpu.config \
--templateflow_home ${TEST_DIR}/TemplateFlow \
--skip_bids_validation \
--device cpu \
--debug \
--resume
```

**Comment by favour-nerrise** [comment]
@NingAnMe  Hiya! Unfortunately still getting the same error when running with `cpu`:

```
ERROR ~ Error executing process > 'bold_wf:bold_synthmorph_affine (sub-03)'

Caused by:
  Process `bold_wf:bold_synthmorph_affine (sub-03)` terminated with an error exit status (1)

Command executed:

  gpu_schedule_run.py cpu double executor /opt/DeepPrep/deepprep/SynthMorph/bold_synthmorph_affine.py     --bold_preprocess_dir /scratch/groups/redacted/data/ppmi_fmri_derivatives/BOLD     --subject_id sub-03     --synth_script /opt/DeepPrep/deepprep/SynthMorph/mri_bold_synthmorph.py     --t1_native2mm /scratch/groups/redacted/data/ppmi_fmri_derivatives/BOLD/sub-03/anat/sub-03_space-T1w_res-2mm_desc-skull_T1w.nii.gz     --template_space MNI152NLin2009cAsym     --synth_model_path /opt/DeepPrep/deepprep/model/SynthMorph/models

Command exit status:
  1

Command output:
  INFO: Device: cpu
  INFO: GPU: 
  INFO: sys.argv : ['/opt/DeepPrep/deepprep/nextflow/bin/gpu_schedule_run.py', 'cpu', 'double', 'executor', '/opt/DeepPrep/deepprep/SynthMorph/bold_synthmorph_affine.py', '--bold_preprocess_dir', '/scratch/groups/redacted/data/ppmi_fmri_derivatives/BOLD', '--subject_id', 'sub-03', '--synth_script', '/opt/DeepPrep/deepprep/SynthMorph/mri_bold_synthmorph.py', '--t1_native2mm', '/scratch/groups/redacted/data/ppmi_fmri_derivatives/BOLD/sub-03/anat/sub-03_space-T1w_res-2mm_desc-skull_T1w.nii.gz', '--template_space', 'MNI152NLin2009cAsym', '--synth_model_path', '/opt/DeepPrep/deepprep/model/SynthMorph/models']
  Cant connect to StrictRedis DB: Error 111 connecting to localhost:6379. Connection refused.
  INFO: GPU: python3 /opt/DeepPrep/deepprep/SynthMorph/bold_synthmorph_affine.py --bold_preprocess_dir /scratch/groups/redacted/data/ppmi_fmri_derivatives/BOLD --subject_id sub-03 --synth_script /opt/DeepPrep/deepprep/SynthMorph/mri_bold_synthmorph.py --t1_native2mm /scratch/groups/redacted/data/ppmi_fmri_derivatives/BOLD/sub-03/anat/sub-03_space-T1w_res-2mm_desc-skull_T1w.nii.gz --template_space MNI152NLin2009cAsym --synth_model_path /opt/DeepPrep/deepprep/model/SynthMorph/models
  Downloading https://templateflow.s3.amazonaws.com/tpl-MNI152NLin2009cAsym/tpl-MNI152NLin2009cAsym_res-02_T1w.nii.gz
  Traceback (most recent call last):
    File "/opt/DeepPrep/deepprep/SynthMorph/bold_synthmorph_affine.py", line 40, in <module>
      template = tflow.get(args.template_space, desc=None, resolution=2, suffix='T1w', extension='nii.gz')
    File "/usr/local/lib/python3.10/dist-packages/templateflow/conf/__init__.py", line 69, in wrapper
      return func(*args, **kwargs)
    File "/usr/local/lib/python3.10/dist-packages/templateflow/api.py", line 145, in get
      _s3_get(filepath)
    File "/usr/local/lib/python3.10/dist-packages/templateflow/api.py", line 308, in _s3_get
      with filepath.open("wb") as f:
    File "/usr/lib/python3.10/pathlib.py", line 1119, in open
      return self._accessor.open(self, mode, buffering, encoding, errors,
  OSError: [Errno 30] Read-only file system: '/opt/TemplateFlow/tpl-MNI152NLin2009cAsym/tpl-MNI152NLin2009cAsym_res-02_T1w.nii.gz'

Command error:
  WARNING: SINGULARITYENV_TMPDIR and APPTAINERENV_TMPDIR have different values, using the latter
  INFO:    Environment variable SINGULARITYENV_NXF_DEBUG is set, but APPTAINERENV_NXF_DEBUG is preferred
  WARNING: Skipping environment variable [SINGULARITYENV_TMPDIR=/tmp], TMPDIR is already overridden with different value [/scratch/groups/redacted/data/ppmi_fmri_derivatives/WorkDir/tmp]
  Traceback (most recent call last):
    File "/opt/DeepPrep/deepprep/nextflow/bin/gpu_schedule_run.py", line 76, in <module>
      assert status == 0
  AssertionError

Work dir:
  /scratch/groups/redacted/data/ppmi_fmri_derivatives/WorkDir/nextflow/e8/276e02b8495662fcac9fc13eb8a8ec

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

 -- Check '.nextflow.log' file for details
```

or `gpu`
```
ERROR ~ Error executing process > 'bold_wf:bold_synthmorph_affine (sub-03)'

Caused by:
  Process `bold_wf:bold_synthmorph_affine (sub-03)` terminated with an error exit status (1)

Command executed:

  gpu_schedule_run.py gpu double executor /opt/DeepPrep/deepprep/SynthMorph/bold_synthmorph_affine.py     --bold_preprocess_dir /scratch/groups/kpohl/data/ppmi_fmri_derivatives/BOLD     --subject_id sub-03     --synth_script /opt/DeepPrep/deepprep/SynthMorph/mri_bold_synthmorph.py     --t1_native2mm /scratch/groups/kpohl/data/ppmi_fmri_derivatives/BOLD/sub-03/anat/sub-03_space-T1w_res-2mm_desc-skull_T1w.nii.gz     --template_space MNI152NLin2009cAsym     --synth_model_path /opt/DeepPrep/deepprep/model/SynthMorph/models

Command exit status:
  1

Command output:
  INFO: Device: gpu
  Auto select GPU by ： gpu
  GPU INFO:
  ['0, NVIDIA GeForce RTX 2080 Ti, 11010 MiB, 11264 MiB, 24.39 W, 224.00 W\n']
  GPU INFO:
  ['0, NVIDIA GeForce RTX 2080 Ti, 11010 MiB, 11264 MiB, 24.39 W, 224.00 W\n']
  Choosing the GPU device has largest free memory...
  Sorted by free memory size
  Using GPU 0:
  index:0
  gpu_name:NVIDIA GeForce RTX 2080 Ti
  memory.free:11010
  memory.total:11264
  power.draw:24
  power.limit:224
  specified:False
  INFO: GPU: 0
  INFO: sys.argv : ['/opt/DeepPrep/deepprep/nextflow/bin/gpu_schedule_run.py', 'gpu', 'double', 'executor', '/opt/DeepPrep/deepprep/SynthMorph/bold_synthmorph_affine.py', '--bold_preprocess_dir', '/scratch/groups/redacted/data/ppmi_fmri_derivatives/BOLD', '--subject_id', 'sub-03', '--synth_script', '/opt/DeepPrep/deepprep/SynthMorph/mri_bold_synthmorph.py', '--t1_native2mm', '/scratch/groups/redacted/data/ppmi_fmri_derivatives/BOLD/sub-03/anat/sub-03_space-T1w_res-2mm_desc-skull_T1w.nii.gz', '--template_space', 'MNI152NLin2009cAsym', '--synth_model_path', '/opt/DeepPrep/deepprep/model/SynthMorph/models']
  Cant connect to StrictRedis DB: Error 111 connecting to localhost:6379. Connection refused.
  INFO: GPU: python3 /opt/DeepPrep/deepprep/SynthMorph/bold_synthmorph_affine.py --bold_preprocess_dir /scratch/groups/redacted/data/ppmi_fmri_derivatives/BOLD --subject_id sub-03 --synth_script /opt/DeepPrep/deepprep/SynthMorph/mri_bold_synthmorph.py --t1_native2mm /scratch/groups/redacted/data/ppmi_fmri_derivatives/BOLD/sub-03/anat/sub-03_space-T1w_res-2mm_desc-skull_T1w.nii.gz --template_space MNI152NLin2009cAsym --synth_model_path /opt/DeepPrep/deepprep/model/SynthMorph/models
  Downloading https://templateflow.s3.amazonaws.com/tpl-MNI152NLin2009cAsym/tpl-MNI152NLin2009cAsym_res-02_T1w.nii.gz
  Traceback (most recent call last):
    File "/opt/DeepPrep/deepprep/SynthMorph/bold_synthmorph_affine.py", line 40, in <module>
      template = tflow.get(args.template_space, desc=None, resolution=2, suffix='T1w', extension='nii.gz')
    File "/usr/local/lib/python3.10/dist-packages/templateflow/conf/__init__.py", line 69, in wrapper
      return func(*args, **kwargs)
    File "/usr/local/lib/python3.10/dist-packages/templateflow/api.py", line 145, in get
      _s3_get(filepath)
    File "/usr/local/lib/python3.10/dist-packages/templateflow/api.py", line 308, in _s3_get
      with filepath.open("wb") as f:
    File "/usr/lib/python3.10/pathlib.py", line 1119, in open
      return self._accessor.open(self, mode, buffering, encoding, errors,
  OSError: [Errno 30] Read-only file system: '/opt/TemplateFlow/tpl-MNI152NLin2009cAsym/tpl-MNI152NLin2009cAsym_res-02_T1w.nii.gz'

Command error:
  INFO:    Environment variable SINGULARITYENV_TMPDIR is set, but APPTAINERENV_TMPDIR is preferred
  INFO:    Environment variable SINGULARITYENV_NXF_DEBUG is set, but APPTAINERENV_NXF_DEBUG is preferred
  INFO:    underlay of /usr/bin/nvidia-smi required more than 50 (455) bind mounts
  Traceback (most recent call last):
    File "/opt/DeepPrep/deepprep/nextflow/bin/gpu_schedule_run.py", line 76, in <module>
      assert status == 0
  AssertionError

Work dir:
  /scratch/groups/redacted/data/ppmi_fmri_derivatives/WorkDir/nextflow/da/a67eb0f02746bc587f4216b035848d

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line

 -- Check '.nextflow.log' file for details
```

My `deepprep_gpu.sh` script is:
```
#!/bin/bash
#
#SBATCH --job-name=deepprep_02
#SBATCH --output=deepprep_.%j.out
#SBATCH --error=deepprep_.%j.err
#SBATCH --time=2:00:00
#SBATCH --gres=gpu:1
#SBATCH --constraint=GPU_SKU:V100_PCIE
#SBATCH --cpus-per-task=8
#SBATCH --mem=16G
#SBATCH -p gpu
#SBATCH --mail-type=ALL


module load python/3.9.0
module load cuda/12.4.0
module load biology
module load nextflow/23.04.3
module load java/18.0.2
module load redis/4.0.1

export TEST_DIR=/scratch/groups/redacted/data
bids_root_dir=/scratch/groups/redacted/data/PPMI_fmri

cd ${TEST_DIR}
git clone --recurse-submodules https://github.com/pBFSLab/DeepPrep.git

export FS_LICENSE=$bids_root_dir/derivatives/freesurfer_license.txt
export BIDS_PATH=$bids_root_dir
export OUTPUT_PATH=${TEST_DIR}/ppmi_fmri_derivatives

${TEST_DIR}/DeepPrep/deepprep/deepprep.sh \
${BIDS_PATH} \
${OUTPUT_PATH} \
participant \
--participant_label sub-03 \
--bold_task_type rest \
--bold_volume_space MNI152NLin2009cAsym \
--deepprep_home ${TEST_DIR}/DeepPrep \
--fs_license_file ${FS_LICENSE} \
--executor cluster \
--container ${TEST_DIR}/deepprep_23.1.0.sif \
--config_file ${TEST_DIR}/deepprep.slurm.gpu.config \
--templateflow_home ${TEST_DIR}/TemplateFlow \
--skip_bids_validation \
--device gpu \
--debug \
--resume
```

**Comment by Ireneyou33** [comment]
Hi @favour-nerrise, 

As the error reports:

> OSError: [Errno 30] Read-only file system: '/opt/TemplateFlow/tpl-MNI152NLin2009cAsym/tpl-MNI152NLin2009cAsym_res-02_T1w.nii.gz'

It appears that the same problem you came across on both the CPU and GPU is due to the **permission** of the `Templateflow` directory. We recommend changing the permission of that folder to 755 or 777, and try again.

good luck!

**Comment by NingAnMe** [comment]
Hi @favour-nerrise,

We have resolved this issue in the new version, you can pull the latest Singularity image to try it.

`curl -C - -O https://download.anning.info/ninganme-public/DeepPrep/SingularityImage/deepprep_24.1.0.sif`
